import { MEDIA, GALLERY_IMAGES, foodImageFor, drinkImageFor } from "./media";

export type SeedCategory = {
  name: string;
  slug: string;
  description: string;
  type: "food" | "drink";
  sortOrder: number;
};

export type SeedMenuItem = {
  name: string;
  slug: string;
  description: string;
  price: number;
  image: string;
  calories?: number;
  prepTime?: number;
  tags: string[];
  categorySlug: string;
  isFeatured?: boolean;
  isNew?: boolean;
  isBestSeller?: boolean;
  isSignature?: boolean;
  isChefPick?: boolean;
  isTodaysSpecial?: boolean;
};

export const SEED_CATEGORIES: SeedCategory[] = [
  { name: "Breakfast", slug: "breakfast", description: "Morning classics and Ethiopian breakfast favorites", type: "food", sortOrder: 1 },
  { name: "Lunch", slug: "lunch", description: "Midday plates crafted for leisurely dining", type: "food", sortOrder: 2 },
  { name: "Dinner", slug: "dinner", description: "Evening cuisine for memorable nights", type: "food", sortOrder: 3 },
  { name: "Traditional Ethiopian Food", slug: "traditional-ethiopian", description: "Authentic flavors of Ethiopia", type: "food", sortOrder: 4 },
  { name: "International Food", slug: "international", description: "Global dishes with a Gize twist", type: "food", sortOrder: 5 },
  { name: "Desserts", slug: "desserts", description: "Sweet finales to your meal", type: "food", sortOrder: 6 },
  { name: "Cocktails", slug: "cocktails", description: "Signature mixed drinks and classics", type: "drink", sortOrder: 7 },
  { name: "Soft Drinks", slug: "soft-drinks", description: "Refreshing non-alcoholic beverages", type: "drink", sortOrder: 8 },
  { name: "Hot Drinks", slug: "hot-drinks", description: "Coffee, tea, and warm comforts", type: "drink", sortOrder: 9 },
  { name: "Wine", slug: "wine", description: "Curated reds, whites, and sparkling", type: "drink", sortOrder: 10 },
  { name: "Beer", slug: "beer", description: "Local and imported selections", type: "drink", sortOrder: 11 },
  { name: "Whiskey", slug: "whiskey", description: "Premium whiskeys and blends", type: "drink", sortOrder: 12 },
  { name: "Vodka", slug: "vodka", description: "Smooth vodkas and pours", type: "drink", sortOrder: 13 },
  { name: "Gin", slug: "gin", description: "Botanical gins and serves", type: "drink", sortOrder: 14 },
];

export const SEED_MENU: SeedMenuItem[] = [
  {
    name: "Gize Breakfast Platter",
    slug: "gize-breakfast-platter",
    description: "Scrambled eggs, sautéed vegetables, toasted bread, Ethiopian cheese, and fresh fruit — a refined start to your day.",
    price: 450,
    image: foodImageFor("breakfast", 0),
    calories: 620,
    prepTime: 20,
    tags: ["breakfast", "platter"],
    categorySlug: "breakfast",
    isFeatured: true,
    isBestSeller: true,
  },
  {
    name: "Avocado Toast Royale",
    slug: "avocado-toast-royale",
    description: "Sourdough topped with smashed avocado, poached eggs, chili oil, and microgreens.",
    price: 380,
    image: foodImageFor("breakfast", 1),
    calories: 480,
    prepTime: 15,
    tags: ["vegetarian", "breakfast"],
    categorySlug: "breakfast",
    isNew: true,
  },
  {
    name: "Ful Medames Bowl",
    slug: "ful-medames-bowl",
    description: "Slow-cooked fava beans with olive oil, berbere spice, tomato, and warm injera on the side.",
    price: 320,
    image: foodImageFor("breakfast", 2),
    calories: 410,
    prepTime: 18,
    tags: ["ethiopian", "breakfast"],
    categorySlug: "breakfast",
  },
  {
    name: "Grilled Chicken Caesar",
    slug: "grilled-chicken-caesar",
    description: "Crisp romaine, aged parmesan, house croutons, and charcoal-grilled chicken breast.",
    price: 520,
    image: foodImageFor("lunch", 0),
    calories: 540,
    prepTime: 22,
    tags: ["salad", "lunch"],
    categorySlug: "lunch",
    isFeatured: true,
  },
  {
    name: "Beef Tenderloin Sandwich",
    slug: "beef-tenderloin-sandwich",
    description: "Seared tenderloin, caramelized onions, horseradish cream, and arugula on a brioche bun.",
    price: 650,
    image: foodImageFor("lunch", 1),
    calories: 720,
    prepTime: 25,
    tags: ["beef", "lunch"],
    categorySlug: "lunch",
    isBestSeller: true,
  },
  {
    name: "Seafood Linguine",
    slug: "seafood-linguine",
    description: "Prawns, mussels, and calamari in a white wine garlic sauce over al dente linguine.",
    price: 780,
    image: foodImageFor("lunch", 2),
    calories: 680,
    prepTime: 30,
    tags: ["seafood", "pasta"],
    categorySlug: "lunch",
    isChefPick: true,
  },
  {
    name: "Wagyu-Style Ribeye",
    slug: "wagyu-style-ribeye",
    description: "300g aged ribeye, smoked butter, roasted bone marrow, and seasonal vegetables.",
    price: 1850,
    image: foodImageFor("dinner", 0),
    calories: 890,
    prepTime: 35,
    tags: ["steak", "dinner", "premium"],
    categorySlug: "dinner",
    isSignature: true,
    isFeatured: true,
    isBestSeller: true,
  },
  {
    name: "Herb-Crusted Lamb Rack",
    slug: "herb-crusted-lamb-rack",
    description: "New Zealand lamb with rosemary crust, mint jus, and potato gratin.",
    price: 1650,
    image: foodImageFor("dinner", 1),
    calories: 820,
    prepTime: 40,
    tags: ["lamb", "dinner"],
    categorySlug: "dinner",
    isChefPick: true,
    isSignature: true,
  },
  {
    name: "Pan-Seared Sea Bass",
    slug: "pan-seared-sea-bass",
    description: "Crispy-skinned sea bass, saffron beurre blanc, fennel salad, and citrus zest.",
    price: 1420,
    image: foodImageFor("dinner", 2),
    calories: 560,
    prepTime: 28,
    tags: ["seafood", "dinner"],
    categorySlug: "dinner",
    isTodaysSpecial: true,
  },
  {
    name: "Doro Wat",
    slug: "doro-wat",
    description: "Our house chicken stew slow-simmered in berbere, served with injera and boiled egg.",
    price: 580,
    image: foodImageFor("traditional-ethiopian", 0),
    calories: 720,
    prepTime: 35,
    tags: ["ethiopian", "spicy", "signature"],
    categorySlug: "traditional-ethiopian",
    isSignature: true,
    isFeatured: true,
    isBestSeller: true,
  },
  {
    name: "Kitfo Special",
    slug: "kitfo-special",
    description: "Finely minced lean beef seasoned with mitmita and niter kibbeh, served with ayib and gomen.",
    price: 720,
    image: foodImageFor("traditional-ethiopian", 1),
    calories: 650,
    prepTime: 20,
    tags: ["ethiopian", "beef"],
    categorySlug: "traditional-ethiopian",
    isChefPick: true,
    isSignature: true,
  },
  {
    name: "Vegetarian Combination",
    slug: "vegetarian-combination",
    description: "A colorful spread of shiro, misir wat, gomen, atkilt, and fresh salad on injera.",
    price: 480,
    image: foodImageFor("traditional-ethiopian", 2),
    calories: 520,
    prepTime: 25,
    tags: ["ethiopian", "vegetarian"],
    categorySlug: "traditional-ethiopian",
    isFeatured: true,
  },
  {
    name: "Tibs Firfir",
    slug: "tibs-firfir",
    description: "Sautéed beef tibs tossed with torn injera, onions, and awaze sauce.",
    price: 550,
    image: foodImageFor("traditional-ethiopian", 3),
    calories: 680,
    prepTime: 22,
    tags: ["ethiopian", "beef"],
    categorySlug: "traditional-ethiopian",
  },
  {
    name: "Chicken Parmesan",
    slug: "chicken-parmesan",
    description: "Crispy breaded chicken, mozzarella, marinara, and basil over spaghetti.",
    price: 680,
    image: foodImageFor("international", 0),
    calories: 780,
    prepTime: 30,
    tags: ["italian", "chicken"],
    categorySlug: "international",
  },
  {
    name: "Thai Green Curry",
    slug: "thai-green-curry",
    description: "Aromatic coconut curry with vegetables, jasmine rice, and fresh herbs.",
    price: 620,
    image: foodImageFor("international", 1),
    calories: 590,
    prepTime: 28,
    tags: ["thai", "spicy"],
    categorySlug: "international",
    isNew: true,
  },
  {
    name: "Classic Cheeseburger",
    slug: "classic-cheeseburger",
    description: "Angus beef patty, aged cheddar, pickles, secret sauce, and hand-cut fries.",
    price: 580,
    image: foodImageFor("international", 2),
    calories: 860,
    prepTime: 20,
    tags: ["burger", "american"],
    categorySlug: "international",
    isBestSeller: true,
  },
  {
    name: "Tiramisù Classico",
    slug: "tiramisu-classico",
    description: "Espresso-soaked ladyfingers, mascarpone cream, and dark cocoa dust.",
    price: 320,
    image: foodImageFor("desserts", 0),
    calories: 420,
    prepTime: 10,
    tags: ["dessert", "italian"],
    categorySlug: "desserts",
    isFeatured: true,
  },
  {
    name: "Chocolate Lava Cake",
    slug: "chocolate-lava-cake",
    description: "Warm molten chocolate cake with vanilla gelato and berry coulis.",
    price: 380,
    image: foodImageFor("desserts", 1),
    calories: 510,
    prepTime: 18,
    tags: ["dessert", "chocolate"],
    categorySlug: "desserts",
    isBestSeller: true,
    isTodaysSpecial: true,
  },
  {
    name: "Gize Sunset",
    slug: "gize-sunset",
    description: "Our signature cocktail — aged rum, passion fruit, lime, and a whisper of Ethiopian honey.",
    price: 450,
    image: drinkImageFor("cocktails", 0),
    calories: 210,
    prepTime: 8,
    tags: ["signature", "cocktail"],
    categorySlug: "cocktails",
    isSignature: true,
    isFeatured: true,
    isBestSeller: true,
  },
  {
    name: "Bole Negroni",
    slug: "bole-negroni",
    description: "Gin, Campari, sweet vermouth, and an orange twist — stirred to perfection.",
    price: 420,
    image: drinkImageFor("cocktails", 1),
    calories: 180,
    prepTime: 6,
    tags: ["classic", "cocktail"],
    categorySlug: "cocktails",
    isChefPick: true,
  },
  {
    name: "Espresso Martini",
    slug: "espresso-martini",
    description: "Vodka, coffee liqueur, and fresh Ethiopian espresso — shaken silky smooth.",
    price: 480,
    image: drinkImageFor("cocktails", 2),
    calories: 220,
    prepTime: 7,
    tags: ["coffee", "cocktail"],
    categorySlug: "cocktails",
    isFeatured: true,
    isNew: true,
  },
  {
    name: "Mojito Royal",
    slug: "mojito-royal",
    description: "White rum, fresh mint, lime, soda, and a float of sparkling wine.",
    price: 400,
    image: drinkImageFor("cocktails", 3),
    calories: 190,
    prepTime: 8,
    tags: ["refreshing", "cocktail"],
    categorySlug: "cocktails",
  },
  {
    name: "Fresh Passion Juice",
    slug: "fresh-passion-juice",
    description: "Pressed passion fruit with a touch of honey and crushed ice.",
    price: 180,
    image: drinkImageFor("soft-drinks", 0),
    calories: 120,
    prepTime: 5,
    tags: ["juice", "fresh"],
    categorySlug: "soft-drinks",
  },
  {
    name: "House Lemonade",
    slug: "house-lemonade",
    description: "Fresh lemon, mint, and sparkling water — bright and cooling.",
    price: 150,
    image: drinkImageFor("soft-drinks", 1),
    calories: 90,
    prepTime: 5,
    tags: ["lemonade"],
    categorySlug: "soft-drinks",
  },
  {
    name: "Ethiopian Coffee Ceremony Cup",
    slug: "ethiopian-coffee",
    description: "Single-origin beans roasted and brewed in the traditional ceremony style.",
    price: 120,
    image: drinkImageFor("hot-drinks", 0),
    calories: 5,
    prepTime: 15,
    tags: ["coffee", "ethiopian"],
    categorySlug: "hot-drinks",
    isSignature: true,
    isFeatured: true,
  },
  {
    name: "Spiced Chai Latte",
    slug: "spiced-chai-latte",
    description: "Black tea steeped with cardamom, cinnamon, ginger, and steamed milk.",
    price: 160,
    image: drinkImageFor("hot-drinks", 1),
    calories: 180,
    prepTime: 8,
    tags: ["tea", "spiced"],
    categorySlug: "hot-drinks",
  },
  {
    name: "House Cabernet Sauvignon",
    slug: "house-cabernet",
    description: "Full-bodied red with notes of blackcurrant, cedar, and soft tannins. Glass or bottle.",
    price: 350,
    image: drinkImageFor("wine", 0),
    calories: 150,
    prepTime: 2,
    tags: ["red", "wine"],
    categorySlug: "wine",
    isFeatured: true,
  },
  {
    name: "Chardonnay Reserve",
    slug: "chardonnay-reserve",
    description: "Elegant white with citrus, vanilla oak, and a clean finish.",
    price: 380,
    image: drinkImageFor("wine", 1),
    calories: 140,
    prepTime: 2,
    tags: ["white", "wine"],
    categorySlug: "wine",
  },
  {
    name: "St. George Lager",
    slug: "st-george-lager",
    description: "Crisp Ethiopian lager — the perfect companion to spicy tibs.",
    price: 120,
    image: drinkImageFor("beer", 0),
    calories: 150,
    prepTime: 2,
    tags: ["local", "beer"],
    categorySlug: "beer",
    isBestSeller: true,
  },
  {
    name: "Craft IPA",
    slug: "craft-ipa",
    description: "Hop-forward craft IPA with citrus aroma and a dry bitter finish.",
    price: 180,
    image: drinkImageFor("beer", 1),
    calories: 180,
    prepTime: 2,
    tags: ["craft", "beer"],
    categorySlug: "beer",
    isNew: true,
  },
  {
    name: "Johnnie Walker Black",
    slug: "johnnie-walker-black",
    description: "Iconic blended Scotch — smooth smoke, dried fruit, and spice. Served neat or on the rocks.",
    price: 450,
    image: drinkImageFor("whiskey", 0),
    calories: 110,
    prepTime: 2,
    tags: ["scotch", "whiskey"],
    categorySlug: "whiskey",
    isFeatured: true,
  },
  {
    name: "Jameson Irish Whiskey",
    slug: "jameson",
    description: "Triple-distilled Irish whiskey with notes of vanilla, spice, and sherry.",
    price: 380,
    image: drinkImageFor("whiskey", 1),
    calories: 105,
    prepTime: 2,
    tags: ["irish", "whiskey"],
    categorySlug: "whiskey",
  },
  {
    name: "Grey Goose",
    slug: "grey-goose",
    description: "Premium French vodka — exceptionally smooth, ideal for martinis.",
    price: 420,
    image: drinkImageFor("vodka", 0),
    calories: 100,
    prepTime: 2,
    tags: ["premium", "vodka"],
    categorySlug: "vodka",
  },
  {
    name: "Absolut Elyx",
    slug: "absolut-elyx",
    description: "Copper-crafted vodka with a rich, silky texture.",
    price: 400,
    image: drinkImageFor("vodka", 1),
    calories: 100,
    prepTime: 2,
    tags: ["premium", "vodka"],
    categorySlug: "vodka",
    isNew: true,
  },
  {
    name: "Hendrick's Gin",
    slug: "hendricks-gin",
    description: "Infused with rose and cucumber — botanical and delightfully unusual.",
    price: 420,
    image: drinkImageFor("gin", 0),
    calories: 110,
    prepTime: 2,
    tags: ["botanical", "gin"],
    categorySlug: "gin",
    isFeatured: true,
  },
  {
    name: "Bombay Sapphire",
    slug: "bombay-sapphire",
    description: "Ten botanicals vapor-infused for a bright, aromatic gin experience.",
    price: 380,
    image: drinkImageFor("gin", 1),
    calories: 110,
    prepTime: 2,
    tags: ["classic", "gin"],
    categorySlug: "gin",
  },
];

export const SEED_EVENTS = [
  {
    title: "Friday Live Jazz Night",
    slug: "friday-live-jazz",
    description:
      "Unwind to the smooth sounds of Addis Ababa's finest jazz musicians every Friday. Enjoy signature cocktails, candlelit tables, and an atmosphere made for lingering. Doors open at 8 PM; live set begins at 9 PM.",
    shortDesc: "Live jazz, craft cocktails, and candlelit evenings every Friday.",
    image: MEDIA.events.celebration,
    category: "live-music",
    price: "Free entry · Reservations recommended",
    capacity: 80,
    isFeatured: true,
    daysAhead: 2,
  },
  {
    title: "Birthday Celebration Package",
    slug: "birthday-package",
    description:
      "Celebrate your special day with a dedicated table, complimentary cake, champagne toast for the guest of honor, and a personalized playlist. Our team handles décor accents and photo moments so you can enjoy the night.",
    shortDesc: "Dedicated table, cake, champagne toast, and personal touches.",
    image: MEDIA.events.aisle,
    category: "birthday",
    price: "From 8,500 ETB",
    capacity: 20,
    isFeatured: true,
    daysAhead: 14,
  },
  {
    title: "Corporate Dining Experience",
    slug: "corporate-package",
    description:
      "Impress clients and reward teams with a private dining setup, AV support on request, customized menus, and seamless service. Ideal for product launches, board dinners, and team celebrations in the heart of Bole.",
    shortDesc: "Private dining, AV support, and customized corporate menus.",
    image: MEDIA.events.stage,
    category: "corporate",
    price: "Custom quote",
    capacity: 60,
    isFeatured: false,
    daysAhead: 21,
  },
  {
    title: "Graduation Night",
    slug: "graduation-celebration",
    description:
      "Honor academic milestones with a festive group menu, photo-worthy décor, and a celebratory dessert course. Perfect for families and friends gathering after commencement.",
    shortDesc: "Group menus and festive décor for graduation nights.",
    image: MEDIA.events.chefs,
    category: "graduation",
    price: "From 6,500 ETB",
    capacity: 40,
    isFeatured: false,
    daysAhead: 30,
  },
  {
    title: "Private Chef's Dinner",
    slug: "private-dinner",
    description:
      "An intimate multi-course tasting menu curated by our executive chef, paired with wines or mocktails. Ideal for anniversaries, proposals, and exclusive gatherings of up to twelve guests.",
    shortDesc: "Multi-course tasting for intimate private gatherings.",
    image: MEDIA.events.celebration,
    category: "private-dinner",
    price: "From 12,000 ETB",
    capacity: 12,
    isFeatured: true,
    daysAhead: 10,
  },
  {
    title: "Wedding Celebration Reception",
    slug: "wedding-celebration",
    description:
      "Host your wedding reception or engagement dinner in an elegant setting with floral coordination support, custom menus, and dedicated service staff. We create a night as unforgettable as your love story.",
    shortDesc: "Elegant receptions with custom menus and dedicated service.",
    image: MEDIA.events.aisle,
    category: "wedding",
    price: "Custom quote",
    capacity: 100,
    isFeatured: true,
    daysAhead: 45,
  },
];

export const SEED_TESTIMONIALS = [
  {
    name: "Sara Mekonnen",
    role: "Food Critic, Addis Life",
    content:
      "Gize delivers a rare balance of authentic Ethiopian soul and international polish. The Doro Wat is unforgettable, and the cocktail program rivals any lounge in the city.",
    rating: 5,
    isFeatured: true,
  },
  {
    name: "Daniel Habte",
    role: "Regular Guest",
    content:
      "We celebrated our anniversary with the private chef's dinner — flawless service, beautiful plating, and a room that felt entirely ours. Already booking again.",
    rating: 5,
    isFeatured: true,
  },
  {
    name: "Helen Tesfaye",
    role: "Event Planner",
    content:
      "Corporate dinners at Gize always impress my clients. The team is responsive, the space is elegant, and the food never disappoints.",
    rating: 5,
    isFeatured: true,
  },
  {
    name: "Michael Okonkwo",
    role: "Visitor from Lagos",
    content:
      "One of the best dining experiences I had in Addis. The ambiance is cinematic, the steak was perfect, and the Gize Sunset cocktail is a must.",
    rating: 5,
    isFeatured: true,
  },
  {
    name: "Liya Assefa",
    role: "Local Guide",
    content:
      "I bring guests here for a true taste of modern Addis hospitality. From kitfo to craft cocktails, Gize never misses.",
    rating: 5,
    isFeatured: false,
  },
];

export const SEED_GALLERY = GALLERY_IMAGES.map((g) => ({
  title: g.title,
  image: g.image,
  type: "PHOTO" as const,
  category: g.category,
}));

export const SEED_TEAM = [
  {
    name: "Chef Yonas Bekele",
    role: "Executive Chef",
    bio: "Trained in Addis and Milan, Chef Yonas blends Ethiopian tradition with contemporary technique.",
    image: MEDIA.team.chefs,
  },
  {
    name: "Marta Alemu",
    role: "Bar Manager",
    bio: "Creator of the Gize Sunset and curator of our spirits collection.",
    image: MEDIA.team.chefs,
  },
  {
    name: "Abel Girma",
    role: "Restaurant Manager",
    bio: "Ensuring every guest feels the warmth of Ethiopian hospitality with five-star polish.",
    image: MEDIA.team.chefs,
  },
];

export const WHY_CHOOSE_US = [
  {
    title: "Culinary Excellence",
    description: "From berbere-rich stews to perfectly seared steaks, every plate is crafted with precision and passion.",
  },
  {
    title: "Luxury Ambiance",
    description: "Cinematic lighting, refined interiors, and an atmosphere designed for unforgettable evenings.",
  },
  {
    title: "Craft Cocktail Bar",
    description: "Signature mixes and premium spirits poured by bartenders who treat every drink as an art form.",
  },
  {
    title: "Prime Bole Location",
    description: "Steps behind Mega Building — the heart of Addis Ababa's vibrant dining and nightlife district.",
  },
];

export const STATS = [
  { label: "Years of Excellence", value: 8 },
  { label: "Signature Dishes", value: 40 },
  { label: "Happy Guests", value: 25000 },
  { label: "Events Hosted", value: 500 },
];

export type CateringPackage = {
  id: string;
  name: string;
  slug: string;
  tagline: string;
  price: string;
  guests: string;
  minGuests?: number;
  maxGuests?: number;
  description?: string;
  image?: string;
  featured: boolean;
  highlights: string[];
  status: "PUBLISHED" | "DRAFT" | "ARCHIVED";
  sortOrder: number;
};

export const SEED_CATERING_PACKAGES: CateringPackage[] = [
  {
    id: "pkg-essential",
    name: "Essential Package",
    slug: "essential-package",
    tagline: "Refined simplicity for intimate gatherings",
    price: "From 450 ETB / person",
    guests: "20 – 60 guests",
    minGuests: 20,
    maxGuests: 60,
    description:
      "A complete dining experience with authentic flavors and dedicated staff, ideal for family celebrations, corporate meetings, and private luncheons.",
    image: MEDIA.events.chefs,
    featured: false,
    highlights: [
      "Curated Ethiopian or international 3-course set menu",
      "Professional uniformed service & bar staff",
      "Full tableware setup, linens & clearing",
      "Complimentary tasting & menu consultation",
    ],
    status: "PUBLISHED",
    sortOrder: 1,
  },
  {
    id: "pkg-signature",
    name: "Signature Package",
    slug: "signature-package",
    tagline: "Our most requested gala & reception spread",
    price: "From 750 ETB / person",
    guests: "60 – 150 guests",
    minGuests: 60,
    maxGuests: 150,
    description:
      "Our most popular catering service with live cooking stations, dedicated event captain, custom buffet styling, and complete bar package coordination.",
    image: MEDIA.events.celebration,
    featured: true,
    highlights: [
      "Custom multi-course banquet or gourmet buffet design",
      "Live carving & hot injera specialty stations",
      "Dedicated senior event captain & floor team",
      "Full craft cocktail & beverage bar coordination",
      "Elegant table styling, flowers & layout guidance",
    ],
    status: "PUBLISHED",
    sortOrder: 2,
  },
  {
    id: "pkg-grand",
    name: "Grand Royal Package",
    slug: "grand-royal-package",
    tagline: "Uncompromising luxury for large events & weddings",
    price: "From 1,200 ETB / person",
    guests: "150+ guests",
    minGuests: 150,
    description:
      "The pinnacle of Gize hospitality: executive chefs on-site, bespoke multi-tier menus, VIP service flow, and complete event logistics coordination.",
    image: MEDIA.hero.slide1,
    featured: false,
    highlights: [
      "Bespoke chef tasting & full multi-tier culinary design",
      "Executive Chef & master bartenders on-site",
      "Extended luxury beverage & champagne programs",
      "Complete timeline, logistics & stage coordination",
      "Priority calendar scheduling & VIP dedicated attendants",
    ],
    status: "PUBLISHED",
    sortOrder: 3,
  },
];

